name: "GCC Problem Matcher"

description: "Sets up a problem matcher that's used to create annotations for GCC Warnings and Errors"

author: "electronjoe thanks to xt0rted Template"

branding:
  icon: "command"
  color: "green"

inputs:
  action:
    description: "The action to take on the problem matcher (add or remove)"
    required: false
    default: add

runs:
  using: "node12"
  main: "dist/index.js"
